### PR TITLE
Small documentation fixes

### PR DESCRIPTION
**Pull request by tocram1**
Minor fixes in the documentation I thought would have been cool to do.

### CODE REVIEW

**Comment by tocram1** [comment]
I added a badge to this GitHub repo in the README file, and I rendered this file as an HTML file with [Typora](https://typora.io/) using [Pandoc](https://pandoc.org/), and the [Dark Mint theme](https://theme.typora.io/theme/Mint/).

I don't think there would be an issue with this, but don't hesitate to rework this PR or even reject it just in case.

**Comment by nousr** [comment]
awesome! thanks much, im not at my pc rn but it should be fine to merge when i can sit down 🚀

**Comment by tocram1** [comment]
I fixed the conflict so that you can merge whenever you're able to ;)

**Comment by nousr** [comment]
thanks! 🚀

**Pull request merged**
